// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/templates/GrungePetRecipePlanner-4bP_dM/App.tsx": () => import("../components/mockups/templates/GrungePetRecipePlanner-4bP_dM/App.tsx")
};
